<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Failed: CanRelist = true was not expected]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="4832" started-at="2018-11-15T06:38:17Z" finished-at="2018-11-15T06:38:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4832" started-at="2018-11-15T06:38:17Z" finished-at="2018-11-15T06:38:22Z">
      <class name="com.assurity.rest.test.AssurityApiTest">
        <test-method status="PASS" signature="setBaseUri()[pri:0, instance:com.assurity.rest.test.AssurityApiTest@14acaea5]" name="setBaseUri" is-config="true" duration-ms="833" started-at="2018-11-15T06:38:17Z" finished-at="2018-11-15T06:38:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setBaseUri -->
        <test-method status="FAIL" signature="testCanRelist()[pri:0, instance:com.assurity.rest.test.AssurityApiTest@14acaea5]" name="testCanRelist" duration-ms="3190" started-at="2018-11-15T06:38:18Z" description="Extract the value of canRelist and assert if response is equal to value of Input data" finished-at="2018-11-15T06:38:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed: CanRelist =  true was not expected : expected [false] but found [true]
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed: CanRelist =  true was not expected : expected [false] but found [true]

at org.testng.Assert.fail(Assert.java:96)
at com.assurity.rest.test.AssurityApiTest.testCanRelist(AssurityApiTest.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Failed: CanRelist = true was not expected]]>
            </line>
          </reporter-output>
        </test-method> <!-- testCanRelist -->
        <test-method status="FAIL" signature="testCategoryId()[pri:0, instance:com.assurity.rest.test.AssurityApiTest@14acaea5]" name="testCategoryId" duration-ms="381" started-at="2018-11-15T06:38:21Z" description="Extract the name and assert if response is equal to value of data input" finished-at="2018-11-15T06:38:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed: Name =  Carbon credits was not expected : expected [Carbon credits###] but found [Carbon credits]
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed: Name =  Carbon credits was not expected : expected [Carbon credits###] but found [Carbon credits]

at org.testng.Assert.fail(Assert.java:96)
at com.assurity.rest.test.AssurityApiTest.testCategoryId(AssurityApiTest.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCategoryId -->
        <test-method status="FAIL" signature="testPromotionNameAndCheckDescription()[pri:0, instance:com.assurity.rest.test.AssurityApiTest@14acaea5]" name="testPromotionNameAndCheckDescription" duration-ms="383" started-at="2018-11-15T06:38:21Z" description="Extract name of promotion and image size" finished-at="2018-11-15T06:38:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[FAILED:The Promotions element is not equal to Name = "Ghallery" has a Description does not contains the text  "2hx larger image"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: FAILED:The Promotions element is not equal to Name = "Ghallery" has a Description does not contains the text  "2hx larger image"
at org.testng.Assert.fail(Assert.java:96)
at com.assurity.rest.test.AssurityApiTest.testPromotionNameAndCheckDescription(AssurityApiTest.java:147)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPromotionNameAndCheckDescription -->
      </class> <!-- com.assurity.rest.test.AssurityApiTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
